export default [
  {name: 'Simple Bracelet', source: 'Equipment Shop'},
  {name: 'Simple Necklace', source: 'Equipment Shop'},
  {name: 'Seal of Yu Wang', source: 'Kestrel Guild Shop'},
  {name: 'Crown of Lu Ming', source: 'Moon Tree Guild Shop'},
  {name: 'Medic Badge', source: 'Medic Clerk Guild Shop'},
  {name: '1 Line Reference', source: 'Trifle Clerk Guild Shop'},
  {name: 'Secret News Book', source: 'Empireo Guild Shop'},
  {name: 'Simple Fire Idol', source: 'Equipment Shop'},
  {name: 'Simple Water Idol', source: 'Equipment Shop'},
  {name: 'Simple Wind Idol', source: 'Equipment Shop'},
  {name: 'Simple Earth Idol', source: 'Equipment Shop'},
  {name: 'Simple Steam Ring', source: 'Save Mecha Grunty 5 times'},
  {name: 'Simple Gloves', source: 'DXArmor Shop'},
  {name: 'Simple Earrings', source: 'DXArmor Shop'},
  {name: 'Steam Bracelet', source: 'Save Mecha Grunty 20 times'},
  {name: 'Simple Pendant', source: 'Trifle Clerk Guild Shop'},
  {name: 'Simple Fire Bell', source: 'DXArmor Shop'},
  {name: 'Simple Water Bell', source: 'DXArmor Shop'},
  {name: 'Simple Wind Bell', source: 'DXArmor Shop'},
  {name: 'Simple Earth Bell', source: 'DXArmor Shop'},
  {name: 'Simple Pouch', source: 'Trifle Clerk Guild Shop'},
  {name: 'Simple Head Band', source: 'A reward for saving people'},
  {name: 'Simple Watch', source: 'Trifle Clerk Guild Shop'},
  {name: 'Shadow', source: 'Beat doppleganger'},
  {name: 'Simple Fire Pill', source: 'Buy at Armor Shop in Breg Epona'},
  {name: 'Simple Water Pill', source: 'Buy at Armor Shop in Breg Epona'},
  {name: 'Simple Wind Pill', source: 'Buy at Armor Shop in Breg Epona'},
  {name: 'Simple Earth Pill', source: 'Buy at Armor Shop in Breg Epona'},
  {name: 'Simple Light Pill', source: 'Buy at Armor Shop in Breg Epona'},
  {name: 'Simple Dark Pill', source: 'Buy at Armor Shop in Breg Epona'},
  {name: 'Air Rollershoes', source: 'Rank 1 reward from Mecha Grunty quest'},
  {name: 'Magical Bandage', source: 'Rank 1 reward from Lucky Animal quest'},
  {name: 'Demon Safe Shoes', source: 'Complete "Last Salute of the Goblins" quest'},
  {name: 'Simple Super Hood', source: 'Purchase at Netslum\'s Equipment Shop'},
  {name: 'Simple Auto Clock', source: 'Purchase at Netslum\'s Equipment Shop'},
  {name: 'Simple Star Play', source: 'Purchase at Netslum\'s Equipment Shop'},
  {name: 'Steam Apron', source: 'Rank 2 reward from Mecha Grunty quest'},
  {name: 'Simple Fire Ball', source: 'Chest at (Sigma) Saddened Daybreak\'s Fast Horse'},
  {name: 'Simple Water Ball', source: 'Chest at (Sigma) Counting Leading Fountain'},
  {name: 'Simple Wind Ball', source: 'Chest at (Sigma) Dreaming Humbling Blue Cloud'},
  {name: 'Simple Earth Ball', source: 'Chest at (Sigma) Decadent Humbling Blue Cloud'},
  {name: 'Simple Light Ball', source: 'Chest at (Sigma) Petitioning Mortuary\'s Life'},
  {name: 'Simple Dark Ball', source: 'Chest at (Sigma) Dejected Barren Royal Edict'},
  {name: 'Steam Shield', source: 'Rank 4 reward from Mecha Grunty quest'},
  {name: 'Simple Man Gloves', source: 'Trade with Ookami Itto'},
  {name: 'Simple Jump Clogs', source: 'Trade with Shirochan'},
  {name: 'Simple Fate Book', source: 'Trade with Dragonfly'},
  {name: 'Guide to Divinity', source: 'Complete Forest of Pain'},
  {name: 'Simple Slant Hood', source: 'Chest at (Sigma) Unselfish Kourin\'s Venom Fang'},
  {name: 'Simple Super Belt', source: 'Chest at (Sigma) Serene Cursed Arrows'},
  {name: 'Victor\'s Brooch', source: 'Purchase at Crusade\'s Guild Shop in Breg Epona'},
  {name: 'Badass Uniform', source: 'Purchase at Gem\'s Guild Shop in Breg Epona'},
  {name: 'Empty Eye of Sin', source: 'Azure Kite, Azure Orca, and Azure Balmung\'s initial equip'},
]