export default [
  {name: 'Sub Gear', source: 'Armor Shop in Mercenary District (Mac Anu)'},
  {name: 'Sub Robe', source: 'Armor Shop in Mercenary District (Mac Anu)'},
  {name: 'Sub Gown', source: 'Dropped by Goblin Mage'},
  {name: 'Sub Attire', source: 'DX Armor Shop in Alchemy District (Mac Anu)'},
  {name: 'Sub Yin Yang', source: 'DX Armor Shop in Alchemy District (Mac Anu)'},
  {name: 'Sub Garment', source: "Chest at (Delta) Spring's Cupid's Windup Box"},
  {name: 'Wild Robe', source: 'Lucky Animal Research Vol 1'},
  {name: 'Sub Cape', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Sub Mantle', source: 'Buy Dol Dona Armor Shop'},
  {name: 'The Unexpected', source: 'Lucky Animal Research Vol 2'},
  {name: 'Sub Frock', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Steam Vest', source: 'Mecha Grunty Rescue Vol 2'},
  {name: 'Sub Suit', source: 'Dropped by Long-Lived'},
  {name: 'Sub Cloak', source: 'Trap Chests at(Theta)Saddened Black Windup Box'},
  {name: 'Sub Dragon', source: 'Dropped by Ignis Tail'},
  {name: 'Sub Dress', source: 'Armor Shop Breg Epona'},
  {name: 'Sub Shawl', source: 'Buy from knights guild in Breg Epona'},
  {name: 'Sub Habit', source: 'Weapon Shop Tartarga'},
  {name: 'Sub Vestment', source: 'Dropped by Long-Lived-King'},
  {name: 'Cloak of Eight', source: 'Lucky Animal Research Reward'},
  {name: 'Sub Cowl', source: 'Dropped by Magi Ramon'},
  {name: 'Sub Comet', source: 'Dropped by Lava Dodo'},
  {name: 'Enlightened Cape', source: 'Lucky Animal Research Reward'},
  {name: 'Loose Sash', source: 'Armor Shop in Mercenary District (Mac Anu)'},
  {name: 'Loose Guard', source: 'Armor Shop in Mercenary District (Mac Anu)'},
  {name: 'Loose Kimono', source: 'Dropped by Gigamouth'},
  {name: 'Loose Vest', source: 'Dropped by Elder Growth'},
  {name: 'Loose Plate', source: 'DX Armor Shop in Alchemy District'},
  {name: 'Loose Sheath', source: 'Dropped by Apititer'},
  {name: 'Loose Leather', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Steam Coat', source: 'Mecha Grunty Rescue Vol 2'},
  {name: 'Loose Fur', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Golden Lion', source: 'Lucky Animal Research vol 2'},
  {name: 'Loose Guardian', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Loose Scales', source: 'Chest at (Theta) Unselfish Exposed Windup Box'},
  {name: 'Loose Case', source: 'Trap Chests at(Theta)Saddened Black Windup Box'},
  {name: 'Loose Lionel', source: 'Dropped by Forest King'},
  {name: 'Loose Papa', source: 'Armor Shop Breg Epona'},
  {name: 'Loose Battle', source: 'Dropped by Raid Liger'},
  {name: 'Shelled Uniform', source: 'Lucky Animal Research Reward'},
  {name: 'Loose Wyvern', source: 'Weapon Shop Tartarga'},
  {name: 'Steam War Suit', source: 'Mecha Grunty Rescue Reward'},
  {name: 'Loose Regalia', source: 'Dropped by Trapspore'},
  {name: 'Loose Dispel', source: 'Dropped by TeLe Tali'},
  {name: 'Loose Holy', source: 'Dropped by Chaos Empress'},
  {name: 'Empty Demon Suit', source: 'Post Game Character starts with it'},
  {name: 'Rough Armor', source: 'Armor Shop in Mercenary District (Mac Anu)'},
  {name: 'Rough Shell', source: 'Dropped by Wild Kettle'},
  {name: 'Steam Plate', source: 'Chim Chim Research Vol 1'},
  {name: 'Rough Mail', source: 'Dropped by Steam Shell'},
  {name: 'Rough Defense', source: 'Dropped by Buster Kettle'},
  {name: 'Rough Jiongjia', source: 'DX Armor Shop in Alchemy District (Mac Anu)'},
  {name: 'Steam Armor', source: 'Mecha Grunty Rescue Vol 1'},
  {name: 'Rough Metal', source: 'DX Armor Shop in Alchemy District (Mac Anu)'},
  {name: 'Rough Alloy', source: 'Dropped by Horned Archelon'},
  {name: 'Black Armor', source: 'Abyss Quest Vol 1'},
  {name: 'Steam Suit', source: 'Mecha Grunty Rescue Vol 1'},
  {name: 'Rough Steel', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Whistle Armor', source: 'Lucky Animal Research Vol 2'},
  {name: 'Rough Wave', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Rough Buddha', source: 'Buy Dol Dona Armor Shop'},
  {name: 'Mountaineer Vest', source: 'Lucky Animal Research Vol 2'},
  {name: 'Rough Iron', source: 'Dropped by Process Gear'},
  {name: 'Rough Amalgam', source: 'Dropped by Hash Chase'},
  {name: 'Steam Battle Pod', source: 'Mecha Grunty Rescue Vol 2'},
  {name: 'Summit King', source: 'Lucky Animal Research'},
  {name: 'Rough Dragon', source: 'Dropped by Olin Pack'},
  {name: 'Invincible Shell', source: 'Bounty Hunter Side Job Reward'},
  {name: 'Rough Tiger', source: 'Armor Shop Breg Epona'},
  {name: 'Rough Puma', source: 'Dropped by Brigandine'},
  {name: 'Rough Red Bone', source: 'Dropped by Sir Unknown'},
  {name: 'Rough Diamond', source: 'Weapon Shop Tartarga'},
  {name: 'Rough Imperial', source: 'Dropped by Death Radar'},
  {name: 'Rough Mercury', source: 'Trade with Eddie'},
  {name: 'Other Self', source: 'Defeat Dopple Post Game'},
  {name: 'Dragon Rage', source: 'Lucky Animal Research Reward'},
  {name: 'Rainbow Scale', source: 'Dropped by God Eater'},
  {name: 'Superhero Suit', source: 'Mecha Grunty Rescue Reward'},
  {name: "Emperor's Armor", source: 'Lucky Animal Research Reward'},
  {name: 'Rough Monarch', source: 'Trade with TomCat'},
]
