export default [
  {name: 'Fire Storm', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Fire Barrel', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Tidal Wave', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Water Dragon', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Tornado', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Hurrican Razor', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Earth Spike', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Earth Rain', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Light Arrows', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Holy Arrows', source: 'Buy at Magic Shop in Breg Epona'},
  {name: 'Air Stroke', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Hell Raiser', source: 'Buy at Magic Shop in Breg Epona'},
  {name: 'Health Drink', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Healing Serum', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Healing Potion', source: 'Buy at Trade Store Dol Dona'},
  {name: 'Healing Tonic', source: 'Trade with Zelkova'},
  {name: 'Healing Rain', source: 'Dropped by Lady Guard'},
  {name: 'Revive Rain', source: 'Dropped by Hell Vulture'},
  {name: 'Healing Storm', source: 'Dropped by Gimmick Torch'},
  {name: 'Revive Storm', source: 'Breakables at (Sigma)Ignorant Muddled Two Wings'},
  {name: 'Sprite Drop', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Fairy Drop', source: 'Buy at Trade Store Dol Dona'},
  {name: 'Elven Drop', source: 'Trade with Zelkova'},
  {name: 'Sprite Rain', source: 'Dropped by Living Tower'},
  {name: 'Fairy Rain', source: 'Trade with Tiphereth'},
  {name: 'Elven Rain', source: 'Trade with Kaki Leader'},
  {name: 'Weird Black Tea', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Strange Coffee', source: 'Dropped by Long-Lived-Lord'},
  {name: 'Special Tea', source: 'Trade with Aryosha'},
  {name: 'Holy Potion', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Godly Potion', source: 'Breakables of Block 56 or 57 of Forest of Pain'},
  {name: 'Wonder Potion', source: 'Trade with Blue Eye Samurai or Sky or Yoko'},
  {name: 'Antidote Soda', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Stimulant Soda', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Blessing Soda', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Solution Soda', source: 'Buy at Trade Store Dol Dona'},
  {name: 'Esthesio Soda', source: 'Buy at Trade Store Dol Dona'},
  {name: 'Lucid Soda', source: 'Buy at Trade Shop in Breg Epona'},
  {name: 'Wonder Soda', source: 'Buy at Trade Shop in Breg Epona'},
  {name: 'Omnipotent Soda', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Revival Medicine', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Revive Potion', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Revival Serum', source: 'Bikman Flyer Reward'},
  {name: 'Asian Mango', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Caramel Sauce', source: 'Shop in the Kiosk (Mac Anu)'},
  {name: 'Restore Drop', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Restore Rain', source: 'Trade with Wang Lin'},
  {name: 'Noble Drop', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Noble Rain', source: 'Trade with OHM(Butt)Rice'},
  {name: 'Strange Soda', source: "Anomalies at (Theta)Dreaming Wrath's Bum"},
  {name: 'Chicha Potion', source: "Anomalies (Sigma) Elegant Aster's Berserker"},
  {name: 'Hadesbane Sailve', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Pure Medallion', source: "Dropped by Darklord's Shade"},
  {name: 'Icon of Purity', source: 'Dropped by The One Death'},
  {name: 'Vital Talisman', source: 'Buy at Trade Store Dol Dona'},
  {name: 'Spirit Talisman', source: 'Buy at Trade Store Dol Dona'},
  {name: 'Vital Charm', source: 'Buy at Trade Shop in Breg Epona'},
  {name: 'Spirit Charm', source: 'Buy at Trade Shop in Breg Epona'},
  {name: 'Speed Talisman', source: 'Dropped by Chickie Mama'},
  {name: 'Speed Charm', source: 'Buy at Trade Shop in Breg Epona'},
  {name: 'The Death', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'The Moon', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'The Devil', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'The Emperor', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'The Hanged Man', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'The Hermit', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'The Fool', source: 'Buy at Bad @$$ Guild Breg Epona'},
  {name: 'The Lovers', source: 'Buy at Bad @$$ Guild Breg Epona'},
  {name: 'The Wheel', source: 'Buy at Trade Shop in Breg Epona'},
  {name: 'Warrior Blood', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'Knight Blood', source: 'Dropped by Ruby Cutter'},
  {name: 'Wizard Blood', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'Astrologer Blood', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'Warrior Seal', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'Knight Seal', source: 'Buy from Bad @$$ Guild Shop'},
  {name: 'Wizard Seal', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'Astrologer Seal', source: 'Buy from Bad @$$ Guild Shop in Dol Dona'},
  {name: 'Warrior Soul', source: 'Trade with Heavenly Flower'},
  {name: 'Knight Soul', source: 'Dropped by Scissor Byte'},
  {name: 'Wizard Soul', source: 'Trade with Corporal Yano'},
  {name: 'Astrologer Soul', source: 'Trade with Kunio'},
  {name: 'Warrior Chain', source: 'Trade with Eddie'},
  {name: 'Knight Chain', source: 'Trade with Eddie'},
  {name: 'Wizard Chain', source: 'Trade with Boltz'},
  {name: 'Astrologer Chain', source: 'Trade with Abcinian'},
  {name: 'Warrior Tome', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Knight Tome', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Wizard Tome', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Astrologer Tome', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Warrior Trump', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Knight Trump', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Wizard Trump', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Astrologer Trump', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Smoke Screen', source: 'Buy at Dol Dona Kiosk'},
  {name: "Fairy's Orb", source: 'Buy at Dol Dona Kiosk'},
  {name: 'Return Feather', source: 'Buy at Dol Dona Kiosk'},
  {name: 'Return Wing', source: 'Buy at Kiosk in Breg Epona'},
  {name: "Beginner's Text", source: 'Buy at Bad @$$ Guild Breg Epona'},
  {name: 'Master Text', source: 'Buy at Bad @$$ Shop in Breg Epona'},
  {name: "Beginner's Book", source: 'Buy at Bad @$$ Guild Breg Epona'},
  {name: 'Master Book', source: 'Buy at Bad @$$ Shop in Breg Epona'},
  {name: 'Text of Power', source: 'Quests'},
  {name: 'Book of Power', source: 'Quests'},
  {name: 'Text of Stamina', source: 'Quests'},
  {name: 'Book of Stamina', source: 'Quests'},
  {name: 'Text of Wisdom', source: 'Quests'},
  {name: 'Book of Wisdom', source: 'Quests'},
  {name: 'Text of Sense', source: 'Quests'},
  {name: 'Book of Sense', source: 'Quests'},
  {name: 'Word of Vigor', source: 'Quests'},
  {name: 'Dawn Chim Chim', source: 'Virus Core Trading after Lost Weapons all Maxed'},
  {name: 'Word of Spirit', source: 'Quests'},
  {name: 'Dusk Chim Chim', source: 'Chim Data Side Quest Reward'},
  {name: 'Health Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Antidote Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Dawn Bird Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Priest Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Life Scroll', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Resurrect Scroll', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Reflex Scroll', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Repeal Scroll', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Sanity Scroll', source: 'Buy at Magic shop in Breg Epona'},
  {name: 'Hellfire Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Tidal Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Tornado Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Avalance Scroll', source: 'Magic Item Shop in Mercenary District (Mac Anu)'},
  {name: 'Halcyon Scroll', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Abyss Scroll', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Vitality Scroll', source: 'Buy at Magic shop in Dol Dona'},
  {name: 'Chim Crown', source: 'Randomly dropped by Chim King'},
  {name: 'Coupon', source: "Gifts from NPC's you meet in Dungeons/Fields"},
  {name: 'Flyer Radar', source: 'Bikman Flyer Side Quest'},
  {name: 'Animal Radar', source: 'Lucky Animal Side Quest'},
  {name: 'Fairy Queen Orb', source: 'Block 36-39 reward FoP (15 Skill Triggers)'},
  {name: 'Smoke Bomb', source: 'Block 81-84 reward FoP (25 Skill Triggers)'},
  {name: 'Guiding Wings', source: 'Block 61-64 reward FoP (100 Hit Combo)'},
  {name: 'Fire Mouse Skin', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Olm Shell', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Wing of Lufu', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Soil Bug Antenna', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Scorpion Tail', source: 'Lumina Cloth Shop'},
  {name: 'Midoro Flagellum', source: 'Lumina Cloth Shop'},
  {name: 'Sleeping Powder', source: 'Lumina Cloth Shop'},
  {name: 'Mantis Nail', source: 'Dropped by Fat Lancer'},
  {name: 'Bear Paw', source: 'Empireo Guild Shop (Mac Anu)'},
  {name: 'Thunder Deer Hoof', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Dark Lizard Tail', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Astrid Specimen', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Cow Stomach', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Stingray Stinger', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Shark Tooth', source: 'Buy at Material shop Lumina Cloth'},
  {name: 'Niki Baku Tongue', source: 'Buy at Material shop Lumina Cloth'},
  {name: 'Ein Baku Tongue', source: 'Buy at Material shop Lumina Cloth'},
  {name: 'Demon Bat Horn', source: 'Buy at Material shop in Dol Dona'},
  {name: "Maiden's Hair", source: 'Breakables at (Sigma)Elegant asters Berserker'},
  {name: 'Sabertooth Tooth', source: 'Buy at Magic shop in Breg Epona'},
  {name: 'Niki Baku Fur', source: 'Buy at Magic shop in Breg Epona'},
  {name: 'Ein Baku Fur', source: 'Buy at Magic shop in Breg Epona'},
  {name: 'Niki Baku Jawbone', source: 'Rank Reward for Bike course'},
  {name: 'Ein Baku Jawbone', source: 'Rank Reward for Bike course'},
  {name: 'Stopping Moss', source: 'Trade with Bordeaux (Scythe) | Trap Chest Block 94 FoP'},
  {name: 'Anti-Air Compass', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Nutcracker', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Ninja Claw', source: 'Breakables (Theta) Decadent Pocketed Slacker'},
  {name: 'Strategic Fan', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'War Drum', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Nil Strike', source: 'Block 56-59 reward FoP (Defeat 7 Enemy Parties)'},
  {name: 'Nil Theft', source: 'Block 61-64 reward FoP (Defeat 7 Enemy Parties)'},
  {name: 'Nil Madness', source: 'Block 66-69 reward FoP (Defeat 7 Enemy Parties)'},
  {name: 'Nil Defile', source: 'Block 71-74 reward FoP (Defeat 8 Enemy Parties)'},
  {name: 'Nil Ally', source: 'Block 76-79 reward FoP (Defeat 8 Enemy Parties)'},
  {name: 'Nil Charm', source: 'Block 81-84 reward FoP (Defeat 8 Enemy Parties)'},
  {name: 'Nil Encroach', source: 'Block 86-89 reward FoP (Defeat 9 Enemy Parties)'},
  {name: 'Nil Abduct', source: 'Block 91-94 reward FoP (Defeat 9 Enemy Parties)'},
  {name: 'Nil Embrace', source: 'Block 96-99 reward FoP (Defeat 9 Enemy Parties)'},
  {name: 'Ginseng', source: 'Trade with Kunio or Mile'},
  {name: 'Grudge Water', source: 'Defeat all Chaotic PKs'},
  {name: 'Crystal Skull', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Lodestone', source: "Dropped by Boss at (Sigma)Elegant Aster's Berserker"},
  {name: 'Cat Fang', source: 'Buy at the Kiosk in Tartarga'},
  {name: "Shogun's Fan", source: 'Trade with Wise Dragon'},
  {name: 'Fire Serpent Skin', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Jurgl Shell', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Phoenix Feather', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Greatworm Feeler', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Stormbeast Hoof', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Dark Iguana Tail', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Octoscorp Tail', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Starfish', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Iron Cow Stomach', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Gurah Fist', source: 'Farewell Mecha Grunty Quest'},
  {name: 'Hermit Shell', source: 'Buy Defense Armor from Moon Tree Guild (Dol Dona)'},
  {name: 'Turtle Shell', source: 'Buy from Empireo Guild (Mac Anu)'},
  {name: 'Turtle Crest', source: 'Buy from Empireo Guild (Mac Anu)'},
  {name: 'Cleansing Pill', source: 'Lumina Cloth Shop'},
  {name: "Jinx's Bane", source: 'Lumina Cloth Shop'},
  {name: 'Caffeine Drink', source: 'Lumina Cloth Shop'},
  {name: 'Poison Leaf', source: 'Buy from Moon Tree Guild (Mac Anu)'},
  {name: 'Curse Plant', source: 'Buy from Moon Tree Guild (Mac Anu)'},
  {name: 'Dream Wood Leaf', source: 'Buy from Moon Tree Guild (Mac Anu)'},
  {name: 'Body Egg', source: 'D rank (Delta) Dancing Doomed Bum (2 Barrels then leave)'},
  {name: 'Mind Egg', source: 'Customize Demon Suit Dropped by Long-Lived'},
  {name: 'Body Scale', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Mind Scale', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Fire Resist Seal', source: 'Buy from Moontree Guild (Mac Anu)'},
  {name: 'Aqua Board', source: 'Buy from Moon tree Guild (Mac Anu)'},
  {name: 'Calm Propeller', source: 'Buy from Moon tree Guild (Mac Anu)'},
  {name: 'Dustproof Lens', source: 'Buy from Moon tree Guild (Mac Anu)'},
  {name: 'Iron Shell', source: 'Buy from Emperio Guild Shop (Dol Dona)'},
  {name: 'Iron Crest', source: 'Buy from Emperio Guild Shop (Dol Dona)'},
  {name: 'Armadillo Shell', source: 'Dropped by Death Kettle'},
  {name: 'Armadillo Crest', source: 'Dropped by Sorceror Owl'},
  {name: 'Tinted Glass', source: 'Buy from Emperio Guild Shop (Dol Dona)'},
  {name: 'Flash Light', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Opening Cutter', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Fast Glycerin', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Anti-Paralysis', source: 'Buy at Junk shop Dol Dona'},
  {name: 'Blast Leaf', source: 'Dropped by Meggido Hydra'},
  {name: 'Whirlpool Leaf', source: 'Breakables at (Theta) Paling Starting Route'},
  {name: 'Vacuum Leaf', source: 'Breakables (Theta) Ephemeral Times Memoir'},
  {name: 'Desert Rose Leaf', source: 'Dropped by Entowal'},
  {name: 'Flash Leaf', source: "Breakables (Theta) Unselfish Deity's Clepsydra"},
  {name: 'Dark Leaf', source: "Breakables (Theta) Confusing Maiden's Rash Action"},
  {name: 'Coiling Vine', source: "Breakables (Theta) Unselfish Deity's Clepsydra"},
  {name: 'Paralysis Leaf', source: 'Dropped by Druk'},
  {name: 'Body Larva', source: "Breakables at (Theta) Counting Wrath's Bum"},
  {name: 'Mind Larva', source: 'Breakables at (Theta)Decadent Pocketed Slacker'},
  {name: 'Body Wing', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Mind Wing', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Tortoise Shell', source: "Breakables at(Theta)Roaring Discord's Resort"},
  {name: 'Tortoise Crest', source: "Breakables at (Theta) Counting Wrath's Bum"},
  {name: 'Twin Scales', source: "Breakables (Theta) Spring's Discords Resort"},
  {name: 'Steel Shell', source: 'Trade with Oimatsu for Absorb Armor'},
  {name: 'Steel Crest', source: 'Trade with Pen Pen for Holy Armor'},
  {name: 'Sanity Fan', source: 'Trade with Wise Dragon'},
  {name: 'Health Aroma', source: 'Trade with Vergilius'},
  {name: 'Confusion Leaf', source: 'Buy Item Called Delude from Moon Tree Guild Breg Epona'},
  {name: 'Fairyleaf', source: 'Buy Item Called Seduce from Moon Tree Guild Breg Epona'},
  {name: 'Body Butterfly', source: 'Buy Hp +50% armor from knights guild Breg Epona'},
  {name: 'Mind Butter Fly', source: 'Buy Sp +50% armor from knights guild Breg Epona'},
  {name: 'Body Moth', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'Mind Moth', source: 'Buy Empireo guild shop Breg Epona'},
  {name: 'World Mirror', source: 'Defeat Yokochi "Steel" Taro'},
  {name: 'Spirit Tree Bud', source: 'Breakables (Theta)Decadent Pocketed Slacker (Rare)'},
  {name: 'Dual Angel', source: 'Breakables (Theta) Essential Swift Two Wings'},
  {name: 'Broad Angel', source: 'Breakables (Theta) Paling Starting Route'},
  {name: 'Scythe Angel', source: 'Breakables (Theta) Graceful Grieving Drunkered'},
  {name: 'Bayonet Angel', source: "Breakables (Theta) Clever Aster's Hand Song (Rare)"},
  {name: 'Blade Angel', source: "Breakables (Theta) Dreaming Wrath's Bum"},
  {name: 'Gauntlets Angel', source: 'Breakables (Theta) Decadent Pocketed Slacker'},
  {name: 'Lance Angel', source: 'Breakables (Theta) Serene Fighter Runner'},
  {name: 'Staff Angel', source: 'Breakables (Theta) Paling Starting Route'},
  {name: 'Grimore Angel', source: 'Breakables (Theta) Essential Doomed Pure Bred'},
  {name: 'Fan Angel', source: 'Breakables (Theta)Dreaming Doomed Belladonna'},
  {name: 'Phonosheet', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Indulgence', source: 'Rank Reward for Bike course'},
  {name: 'Fire Leaf', source: 'Buy From Material Shop Breg Epona'},
  {name: 'Tide Leaf', source: 'Buy From Material Shop Breg Epona'},
  {name: 'Galegrass', source: 'Buy From Material Shop Breg Epona'},
  {name: 'Stone Rose Petal', source: 'Buy From Material Shop Breg Epona'},
  {name: 'Tomorrowleaf', source: 'Buy From Material Shop Breg Epona'},
  {name: 'Leaf Of Lament', source: 'Buy From Material Shop Breg Epona'},
  {name: 'Toxic Leaf', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Sanctuary Leaf', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Dreamhold Leaf', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Leaf of Binding', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Numbing Lotus', source: 'Buy at the Kiosk in Tartarga'},
  {name: 'Frenzyflower', source: 'Rank Reward for Bike course'},
  {name: 'Charm Leaf', source: 'Rank Reward for Bike course'},
  {name: 'Red Sun Stone', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Blue Moon Ore', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'White Star Sand', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Gray Comet Dust', source: 'Material Shop in Alchemy District (Mac Anu)'},
  {name: 'Gold Snake Skin', source: 'Buy Gp +10% Acc at Guards guild Breg Epona'},
  {name: 'Drowsing Rod', source: 'Buy Drop +10% Acc at Guards guild Breg Epona'},
  {name: 'Amber Dragon Eye', source: 'Buy Exp +25% Acc at Guards guild Breg Epona'},
  {name: 'Evil Snake Skin', source: 'Buy Gp +25% Acc at Guards guild Breg Epona'},
  {name: 'Dowsing Chain', source: 'Buy Drop +25% Acc at Guards guild Breg Epona'},
  {name: 'Gudo Oil', source: 'Buy Item with the name Compress from Guards Guild shop'},
  {name: 'Boost Candle', source: 'Buy Acc called Appraise Guards Guild shop (Dol Dona)'},
  {name: 'Jade Dragon Eye', source: 'Buy Exp +25% Acc at Guards guild Breg Epona'},
  {name: 'Colored Core', source: 'Buy at Material shop in Breg Epona'},
  {name: 'Giant Snake Skin', source: 'Buy at Material shop in Breg Epona'},
  {name: 'Dowsing Board', source: 'Buy from Material Shop Breg Epona'},
  {name: 'Skill Candle', source: 'Buy from Material Shop Breg Epona'},
  {name: 'Vigor Crystal', source: "Breakables at (Sigma)Buzzing Wrath's Belladona"},
  {name: 'Spirit Crystal', source: "Breakables at (Sigma)Winding Wrath's Phoenix"},
  {name: 'Cat Whiskers', source: 'Rank Reward for Bike course'},
  {name: 'Fastbolt Oil', source: 'Rank Reward for Bike course'},
  {name: 'Sapphire Eye', source: 'Buy Exp 50% Acc at Guards Guild shop Breg Epona'},
  {name: 'Time Conch', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Demonic Mallet', source: 'Buy from Emperio Guild shop (Dol Dona)'},
  {name: 'Battle Cosmetics', source: 'Trade with Kunio or Mile'},
  {name: 'True Sun Stone', source: 'Buy from Trifle Guild Shop Breg Epona'},
  {name: 'True Moon Ore', source: 'Rank Reward for Bike course'},
  {name: 'Silver Stardust', source: 'Rank Reward for Bike course'},
  {name: 'Ashen Comet Dust', source: 'Rank Reward for Bike course'},
  {name: 'Seed of Land', source: 'Buy from Empireo guild Breg Epona'},
  {name: 'Grab Bag', source: 'Trade with Wise Dragon'},
  {name: 'Bell of Time', source: 'Buy from Empireo guild Breg Epona'},
  {name: 'Divine Seed', source: 'Rank Reward for Bike course'},
  {name: 'Rosary of Health', source: 'Block 91-94 reward FoP (8 Awakenings)'},
  {name: 'Rosary of Spirit', source: 'Block 96-99 reward FoP (8 Awakenings)'},
]
