export default [
  {name: 'Goblin Rookie', source: '(Delta) Submissive Tragedyï¿¾fs 1000 Oaks'},
  {name: 'Gun Giant', source: "(Delta) Buzzing Aster's Bum"},
  {name: 'Wight Ride', source: 'LotD Quest Vol 1'},
  {name: 'Goblin Mage', source: '(Delta) Upfront Blazing Camellia'},
  {name: 'Gigamouth', source: '(Delta) Essential Bustling Generation'},
  {name: 'Goblin Guard', source: '(Delta) Creeping Wrathï¿¾fs Two Wings'},
  {name: 'Goblin Abyss', source: '(Delta) Piling Returning Hand Song'},
  {name: 'Poisoned Dead', source: 'LotD Quest Vol 1'},
  {name: 'Gurugon', source: 'Gurugon Quest Vol 1'},
  {name: 'Baz Giant', source: '(Delta) Graceful Humbling Holy Relic'},
  {name: 'Living Corpse', source: 'LotD Quest Vol 1'},
  {name: 'Apititer', source: '(Delta) Counting Blazing Berserker'},
  {name: 'Goblin Knight', source: '(Delta) Counting Blazing Foot Stone'},
  {name: 'Goblin Sage', source: '(Theta) Dawning Wrathï¿¾fs Two Wings'},
  {name: 'Giga Bazooka', source: '(Theta) Buzzing Vane Two Wings'},
  {name: 'Steam Goblin', source: '(Theta) Halberd Daybreakï¿¾fs Belladonna'},
  {name: 'Morgul', source: '(Theta) Chaotic Fortified Guard (Abyss Quest V2)'},
  {name: 'Goblin Nemesis', source: '(Theta) Buzzing Returning Phoenix'},
  {name: 'Mono-Grosser', source: '(Theta) Essential Doomed Pure Bred'},
  {name: 'Maxima Bazooka', source: '(Theta) Dreaming Doomed Generation'},
  {name: 'Duster Goblin', source: '(Theta) Galloping Wrathï¿¾fs Pure Bred'},
  {name: 'Zombione', source: 'Abyss Topic area 1 Vol 3'},
  {name: 'Deepone', source: 'Boss for area levels 103-104'},
  {name: 'Goblin General', source: '(Sigma) Developed Bustling Daydream'},
  {name: 'Angelic Gore', source: '(Delta) Truthful Marbleï¿¾fs Bum'},
  {name: 'Fat Lancer', source: '(Delta) Agonizing Blazing Camellia'},
  {name: 'Holy Eater', source: '(Delta) Counting Wrathï¿¾fs Two Wings'},
  {name: 'Cernunnos', source: 'LotD Quest Vol 1'},
  {name: 'Gaze Knight', source: '(Delta) Dawning Red Plumï¿¾fs Berserker'},
  {name: 'Heavens Doom', source: '(Theta) Buzzing Wrathï¿¾fs Phoenix'},
  {name: 'Solid Eye', source: '(Theta) Graceful Wrathï¿¾fs Belladonna'},
  {name: 'Death Eater', source: 'Lost Weapon Guard (Scythe) Vol 2'},
  {name: 'Mirage Banisher', source: 'Lost Weapon Guard (Staff) Vol 2'},
  {name: 'Propagate Stopper', source: 'Lost Weapon Guard (Bayonet) Vol 2'},
  {name: 'Avenge Preventer', source: 'Lost Weapon Guard (Gauntlet) Vol 2'},
  {name: 'Tempt Rejecter', source: 'Lost Weapon Guard (Blade) Vol 2'},
  {name: 'Scheme Breaker', source: 'Lost Weapon Guard (Grimoire) Vol 2'},
  {name: 'Funnyface', source: '(Sigma) Courageous Wrathï¿¾fs Daydream'},
  {name: 'Hell Guardian', source: 'Boss for level 112-114 areas'},
  {name: 'Evil Grinner', source: '(Sigma) Paling Engaging Daydream'},
  {name: 'Horndrigal', source: '(Sigma) Graceful Bustling Belladonna'},
  {name: 'Memento Mori', source: 'Boss for level 121-123 areas'},
  {name: 'Vicious Seed', source: '(Sigma) Graceful Bullï¿¾fs Eye Daydream'},
  {name: 'Magi Ramon', source: '(Sigma) Dreaming Ruined Two Wings'},
  {name: 'The Undying', source: 'Beast of the Seal (Scythe)'},
  {name: 'The Undeceived', source: 'Beast of the Seal (Staff)'},
  {name: 'The Unswayed', source: 'Beast of the Seal (Bayonet)'},
  {name: 'The Unangered', source: 'Beast of the Seal (Gauntlet)'},
  {name: 'The Untempted', source: 'Beast of the Seal (Sword)'},
  {name: 'The Unhidden', source: 'Beast of the Seal (Book)'},
  {name: 'The Uncounseled', source: 'Beast of the Seal (Fan)'},
  {name: 'Duke Orius', source: 'Boss for level 133-135 areas'},
  {name: 'Darklordï¿¾fs Shade', source: 'Block 30 Forest of Pain'},
  {name: 'Mikistri', source: '(Sigma) Winding Wrathï¿¾fs Belladonna'},
  {name: 'True Cernunnos', source: 'Last Boss Forest of Pain'},
  {name: 'Tinder Baron', source: 'Boss for level 148-150 areas'},
  {name: 'Spear Fish', source: '(Delta) Rising Loves Gate'},
  {name: 'Lancer Marine', source: '(Delta) Counting Wrathï¿¾fs Two Wings'},
  {name: 'Sea Trident', source: '(Theta) Counting Wrathï¿¾fs Bum'},
  {name: 'Azul Sachem', source: '(Theta) Springï¿¾fs Wrathï¿¾fs Two Wings'},
  {name: 'Riverdyle', source: '(Sigma) Essential Asterï¿¾fs Bum'},
  {name: 'Mosa Machine', source: 'Steam Professorï¿¾fs Research Quest Vol 3'},
  {name: 'Sea Guathan', source: '(Sigma) Petitioning Blue Silver Utopia'},
  {name: 'Blue Mage', source: '(Sigma) Insightful Swift Two Wings'},
  {name: 'High One', source: 'Block 96 Foesrt of Pain'},
  {name: 'Zan Bezel', source: '(Delta) Wealthy Daybreakï¿¾fs Globe'},
  {name: 'Vak Bezel', source: '(Delta) Submissive Tragedyï¿¾fs 1000 Oaks'},
  {name: 'Gan Bezel', source: '(Delta) Truthful Marbleï¿¾fs Bum'},
  {name: 'Rue Bezel', source: '(Delta) Creeping Vane Camellia'},
  {name: 'Zan Juggler', source: '(Delta) Saddened Humbling Bulwark'},
  {name: 'Vak Juggler', source: '(Delta) Saddened Joyous Shadow'},
  {name: 'Gan Juggler', source: '(Delta) Counting Joyous Shadow'},
  {name: 'Rue Juggler', source: '(Delta) Protected Loveï¿¾fs Bum'},
  {name: 'Lei Zin', source: '(Theta) Troubled Her Antithesis'},
  {name: 'Zan Zin', source: '(Theta) Warm Doomed Generation'},
  {name: 'Rue Zin', source: '(Theta) Paling Leading Phoenix'},
  {name: 'Ani Zin', source: '(Theta) Bequeathed Insatiable Mysteries'},
  {name: 'Gan Zin', source: '(Theta) Paling Doomed Belladonna'},
  {name: 'Vak Zin', source: '(Theta) Saddened Asterï¿¾fs Phoenix'},
  {name: 'Atmosphere', source: '(Sigma) Courageous Asterï¿¾fs Two Wings'},
  {name: 'Chickie', source: '(Delta) Overjoyed Wrathï¿¾fs Berserker'},
  {name: 'Trainee Owl', source: "(Delta) Screaming Aster's Bulwark"},
  {name: 'Raven Claw', source: '(Delta)Croaking Military Whicker'},
  {name: 'Chickie Dada', source: '(Delta) Coiling Friendï¿¾fs Whiplash'},
  {name: 'Scalvenger', source: 'Scalvenger Quest Vol 1'},
  {name: 'Hermit Owl', source: '(Delta) Counting Cupidï¿¾fs Bum'},
  {name: 'Black Raptor', source: '(Delta) Freezing Bustling Whicker'},
  {name: 'Lady Guard', source: '(Theta) Clever Geniusï¿¾fs Moon River'},
  {name: 'Sorceror Owl', source: '(Theta) Halberd Daybreakï¿¾fs Belladonna'},
  {name: 'Chickie Mama', source: '(Theta) Essential Wrathï¿¾fs Dagger'},
  {name: 'Hell Vulture', source: '(Theta) Paling Red Plumï¿¾fs Generation'},
  {name: 'Ignis Tail', source: '(Theta) Galloping Wrathï¿¾fs Pure Bred'},
  {name: 'Wisdom Owl', source: 'Boss for level 101-102 areas'},
  {name: 'Chickie Gramma', source: '(Sigma) Paling Engaging Daydream'},
  {name: 'Harpy Queen', source: '(Sigma) Dreaming Ruined Two Wings'},
  {name: 'Lava Dodo', source: '(Sigma) Winding Asterï¿¾fs Phoenix'},
  {name: 'Onion Mash', source: '(Delta) Submissive Tragedyï¿¾fs 1000 Oaks'},
  {name: 'Crumple Tree', source: '(Delta)Great Cursed In-laws'},
  {name: 'Truffle', source: '(Delta) Piling Red Plumï¿¾fs Twin Rocks'},
  {name: 'Elder Growth', source: '(Delta) Piling Red Plumï¿¾fs Twin Rocks'},
  {name: 'Hanger Berry', source: '(Theta) Buzzing Doomed Pure Bred'},
  {name: 'Entowal', source: '(Theta) Buzzing Doomed Pure Bred'},
  {name: 'Funger Hat', source: '(Theta) Piling Bustling Pure Bred'},
  {name: 'Forest King', source: '(Theta) Galloping Asterï¿¾fs Dagger'},
  {name: 'Trapspore', source: '(Sigma) Decadent Engaging Whicker'},
  {name: 'Rue Fang', source: '(Delta) Buzzing Wrathï¿¾fs Puddle'},
  {name: 'Gan Fang', source: '(Delta) Starting Bustling Holy Ground'},
  {name: 'Bravo Nose', source: "(Delta) Wealthy Dusk's Bum"},
  {name: 'Vak Fang', source: '(Delta) Truthful Forbidden 1000 Oaks'},
  {name: 'Zan Fang', source: '(Delta) Truthful Forbidden 1000 Oaks'},
  {name: 'Ani Fang', source: '(Delta)Spectating Cloudless Hand Song'},
  {name: 'Lei Fang', source: '(Delta) Soulful Swift Alga Grass'},
  {name: 'Zan Ziger', source: '(Delta)Paling Grey Gate'},
  {name: 'Rue Ziger', source: '(Delta) Rising Cursed metal Doll'},
  {name: 'Ani Ziger', source: '(Delta) Thrilling Doomed Two Wings'},
  {name: 'Don Elephant', source: '(Delta) Counting Hereticï¿¾fs Frog Lake'},
  {name: 'Vak Ziger', source: '(Delta) Saddened Returning Shadow'},
  {name: 'Gan Ziger', source: '(Delta) Counting Gamblerï¿¾fs 1000 Oaks'},
  {name: 'Lei Ziger', source: '(Delta) Cheering Exposed Generation'},
  {name: 'Shadowless Dog', source: 'Gathering Shadows Quest Vol 2'},
  {name: 'Mighty Nauman', source: '(Theta) Buzzing Bustling Pure Bred'},
  {name: 'Strange Head', source: '(Theta) Buzzing Wrathï¿¾fs Dagger'},
  {name: 'Olin Pack', source: '(Theta) Counting Wrathï¿¾fs Bum'},
  {name: 'Giga Mammoth', source: '(Theta) Roaring Asterï¿¾fs Phoenix'},
  {name: 'Heatwave Hound', source: 'Dubious Dog Quest Vol 3'},
  {name: 'Raid Liger', source: 'Boss for level 107-109 areas'},
  {name: 'Sir Unknown', source: '(Sigma) Essential Bustling Belladonna'},
  {name: 'Spheranodon', source: 'Boss for level 127-129 areas'},
  {name: 'TeLe Tali', source: 'Boss for level136-138 areas'},
  {name: 'Chaos Empress', source: 'Boss for level 142-144 areas'},
  {name: 'Wild Kettle', source: '(Delta) Buzzing Wrathï¿¾fs Puddle'},
  {name: 'Knuckleman', source: 'Knuckleman Quest Vol 1'},
  {name: 'Buster Kettle', source: '(Delta) Creeping Wrathï¿¾fs Two Wings'},
  {name: 'Steam Shell', source: '(Delta) Rough Song Dusks Hand song'},
  {name: 'Metal Fist', source: '(Delta) Counting Blazing Foot Stone'},
  {name: '#Rain', source: '(Steam Scientist Quest) Vol 2'},
  {name: '#Cloud', source: '(Steam Scientist Quest) Vol 2'},
  {name: 'Death Kettle', source: '(Theta) Blazing Multiple Buttercup'},
  {name: '#Rain Cloud', source: '(Steam Scientist Quest) Vol 2'},
  {name: 'Process Gear', source: '(Theta) Paling Leading Phoenix'},
  {name: 'Gobtank 75', source: '(Theta) Dreaming Swift Belladonna'},
  {name: 'Bowler Head', source: '(Theta) Roaring Swift Belladonna'},
  {name: 'Chain Whip', source: '(Theta) Springï¿¾fs Doomed Belladonna'},
  {name: 'Gobcannon 77', source: '(Theta) Galloping Doomed Two Wing'},
  {name: 'Brigandine', source: 'Boss for level 105-106 areas'},
  {name: 'Tetra Foot', source: '(Sigma) Fading Moonflower Glory'},
  {name: 'Black Gurah', source: 'Farwell Mecha Grunty Quest'},
  {name: 'Proto Gurah', source: 'Farwell Mecha Grunty Quest'},
  {name: 'Gobdam 78', source: '(Sigma) Dreaming Wrathï¿¾fs Belladonna'},
  {name: 'Break Rest', source: '(Sigma) Developed Bullï¿¾fs Eye Daydream'},
  {name: 'Heavy Stamp', source: '(Sigma) Winding Wrathï¿¾fs Belladonna'},
  {name: 'Arachnophobia', source: '(Sigma) Competing Wizardï¿¾fs Daydream'},
  {name: 'Lizard Hunter', source: '(Delta) Truthful Marbleï¿¾fs Bum'},
  {name: 'Lizard Assassin', source: '(Delta) Piling Military Shadow'},
  {name: 'Drygon', source: '(Delta) Blurry Cursed Camellia'},
  {name: 'Fever Horse', source: "(Delta) Graceful Wrath's Shadow"},
  {name: 'Blaze Drake', source: '(Delta) Roaring Wrathï¿¾fs berserker'},
  {name: 'Dryas', source: '(Delta) Roaring Doomed Snow Caps'},
  {name: 'Elite Lizard', source: '(Theta) Buzzing Wrathï¿¾fs Fast Horse'},
  {name: 'Meggido Hydra', source: '(Theta) Essential Wrathï¿¾fs Fast Horse'},
  {name: 'Long-Lived', source: '(Theta) Essential Doomed Pure Bred'},
  {name: 'Dardeus', source: '(Theta) Counting Bustling Generation'},
  {name: 'Long-Lived-Lord', source: '(Theta) Galloping Swift Two Wings'},
  {name: 'Dryramas', source: 'Boss for level 118-120 areas'},
  {name: 'Long-Lived-King', source: '(Sigma) Graceful Bullï¿¾fs Eye Daydream'},
  {name: 'Metal Dragon', source: 'Farwell Mecha Grunty Quest'},
  {name: 'Hecatonfoot', source: "(Delta) Graceful Aster's Pure Bred"},
  {name: 'Carrie', source: '(Delta) Rising Cursed Metal Doll'},
  {name: 'Ruby Cutter', source: '(Delta) Piling Red Plumï¿¾fs Twin Rocks'},
  {name: 'Mad Jaws', source: '(Delta) Disputing Gray Tiny Beast (Crab Monster Quest Vol 1)'},
  {name: 'Great Jaws', source: 'Crab Monster Quest Vol 1'},
  {name: 'Carrianne', source: '(Theta) Counting Red Plumï¿¾fs Shadow'},
  {name: 'Horned Archelon', source: '(Theta) Protected Bustling Weed Eater'},
  {name: 'Fate Crab', source: '(Theta) Dawning Wrathï¿¾fs Two Wingï¿¾fs'},
  {name: 'Masked Beast', source: 'Masquerade Quest Vol 2'},
  {name: 'Tick Mask', source: '(Theta) Buzzing Vane Pure Bred'},
  {name: 'Scorpio ï¿¾e17', source: '(Theta) Warm Bustling Generation'},
  {name: 'Carrizabeth', source: '(Theta) Essential Wrathï¿¾fs Dagger'},
  {name: 'Face Bug', source: '(Theta) Paling Wrathï¿¾fs Phoenix'},
  {name: 'Scissor Byte', source: '(Theta) Dreaming Wrathï¿¾fs Pure Bred'},
  {name: 'Hash Chase', source: '(Theta) Decadent Pocketed Slacker'},
  {name: 'Bison Tortoris', source: '(Theta) Paling Doomed Belladonna'},
  {name: 'Grim Stag', source: '(Sigma) Courageous Wrathï¿¾fs Bum'},
  {name: 'Megalo Adamant', source: 'Boss for level 115-117 areas.'},
  {name: 'Wheel Jack', source: '(Sigma) Graceful Bustling Belladonna'},
  {name: 'Carrionteinne', source: '(Sigma) Developed Bullï¿¾fs Eye Daydream'},
  {name: 'UndeadAnchor Bind', source: '(Theta) Warm Doomed Generation'},
  {name: 'Druk', source: "(Theta)Thrilling Aster's Pure Bred"},
  {name: 'Titan Dead', source: 'Abyss Quest Vol 2'},
  {name: 'Massacre Mummy', source: '(Theta) Galloping Swift Two Wings'},
  {name: 'Blind Pain', source: '(Theta) Roaring Doomed Two Wings'},
  {name: 'Captain Hook', source: '(Sigma) Essential Asterï¿¾fs Bum'},
  {name: 'Death Penalty', source: 'Abyss Topic Area 2'},
  {name: 'Vice Ripper', source: '(Sigma) Confusing Barren Fairy'},
  {name: 'Straight Felon', source: 'Boss for level 124-126 areas'},
  {name: 'Yo-Ho Hyle', source: '(Sigma) Dreaming Wrathï¿¾fs Belladonna'},
  {name: 'Huge Grudge', source: 'Boss for level 139-141 areas'},
  {name: 'Barbarous Ankh', source: '(Sigma) Winding Asters Phoenix'},
  {name: 'Hell Charm', source: '(Theta) Buzzing Doomed Pure Bred'},
  {name: 'Living Tower', source: '(Theta) Piling Bustling Pure Bred'},
  {name: 'Gimmick Torch', source: '(Theta) Roaring Swift Belladonna'},
  {name: 'Break Pillar', source: '(Sigma) Courageous Bustling Bum'},
  {name: '6 Arm Maiden', source: 'Boss for level 110-111 areas'},
  {name: 'Malphas', source: '(Sigma) Essential Engaging Two Wings'},
  {name: 'Death Radar', source: 'Boss for level 130-132 areas'},
  {name: 'Judgement', source: 'Boss for level 145-147 areas'},
  {name: 'Heavenly Ray', source: '(Theta) Unselfish Wrathï¿¾fs Pure Bred'},
  {name: 'Noble Pain', source: '(Sigma) Unselfish Bullï¿¾fs Eye Grey Dance'},
  {name: 'Zan Dibro', source: '(Sigma) Fading Moonflowers Glory'},
  {name: 'Vak Dibro', source: '(Sigma) Essential Bullï¿¾fs Eye Daydream'},
  {name: 'Gan Dibro', source: '(Sigma) Paling Engaging Daydream'},
  {name: 'Lei Dibro', source: '(Sigma) Unselfish Blue Silver Raven'},
  {name: 'Rue Dibro', source: '(Sigma) Paling Wrathï¿¾fs Camellia'},
  {name: 'Ani Dibro', source: '(Sigma) Thrilling Bullï¿¾fs Eye Grey Dance'},
  {name: 'Vak Abado', source: '(Sigma) Competing Blue Silver Utopia'},
  {name: 'Rue Abado', source: '(Sigma) Springï¿¾fs Black Two Wings'},
  {name: 'Zan Abado', source: '(Sigma) Concealed Honor Blue Cloud'},
  {name: 'Gan Abado', source: '(Sigma) Protected Honor Blue Cloud'},
  {name: 'Lei Abado', source: '(Sigma) Competing Blue Silver Utopia'},
  {name: 'Ani Abado', source: '(Sigma) Winding Bullï¿¾fs Eye Fate'},
  {name: 'Last Boss Vol 1'},
  {name: 'Last Boss Vol 2'},
  {name: 'The One Sin', source: 'Abyss Quest Vol 2'},
  {name: 'Bugborn Alpha', source: 'Outer Dungeon 1'},
  {name: 'Bug Queen Alpha', source: 'Outer Dungeon 1'},
  {name: 'God Eater', source: '(Theta) Returning Invincible Huge Beast Vol 2'},
  {name: 'Bugborn beta', source: 'Outer Dungeon 2'},
  {name: 'Bug Queen Beta', source: 'Outer Dungeon 2'},
  {name: 'Bugborn Gamma', source: 'Outer Dungeon 3'},
  {name: 'Bug Queen Gamma', source: 'Outer Dungeon 3'},
  {name: 'Cubia Gomora', source: 'Story Events'},
  {name: 'Ovan', source: 'Story Event'},
  {name: 'Azure Balmung', source: 'Story Event'},
  {name: 'Azure Orca', source: 'Story Event'},
  {name: 'Kite', source: 'Story Event'},
  {name: 'Cubia Core', source: 'Story Event'},
  {name: 'The One Death', source: 'Block 70 Forest of Pain'},
]
