export default [
  {name: 'Spin Gai Gu', source: 'Trap box in (Delta) Fly Away Marbles Windup Box'},
  {name: 'Spin Kouga', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Spin Man Que', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Spin Rasetu', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Spin Corpse', source: 'Dropped by Goblin Guard'},
  {name: 'Spin Locust', source: 'Trap Box in (Delta) Wailing Grieving Windup Box (Random)'},
  {name: 'Spin Ban Mu', source: 'Trap Box in (Delta) Wailing Hardshipï¿¾fs Windup Box(Random)'},
  {name: 'Spin Piney', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Spin Axe', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Dorje Hatchet', source: 'Alkaid Starter Weapon Vol 2'},
  {name: 'Spin Needle', source: 'Buy from Kestrel Guild in Mac Anu'},
  {name: 'Ripper\'s Blade', source: 'Vol 1 Special event (Vol 2 ?)'},
  {name: 'Spin Ribs', source: 'Buy from Weapons Shop(Dol Dona)'},
  {name: 'Spin Indigo', source: 'Buy from Weapons Shop(Dol Dona)'},
  {name: 'Lit Honeysuckle', source: 'Story Event Vol 2'},
  {name: 'Spin Fang', source: 'Dropped by Maxima Bazooka'},
  {name: 'Spin Heaven', source: 'Dropped by Massacre Mummy'},
  {name: 'Heine\'s Invasion', source: 'Transfer Vol 1 data and defeat Dopple'},
  {name: 'Spin Mujin', source: 'Weapon Shop Breg Epona'},
  {name: 'Spin Nezumi', source: 'Dropped by Riverdyle'},
  {name: 'Spin Gorai', source: 'Weapon Shop Tartarga'},
  {name: 'Spin Drake', source: 'Trade with Ubadama'},
  {name: 'Spiral Edge', source: 'Hidden Character Starter Weapon (8th Special PK)'},
  {name: 'Empty Skies', source: 'Story Event'},
  {name: 'Wrath Bringer', source: 'Post Game Arena Challenge Vol 3'},
  {name: 'Broad Demon', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Broad Wheel', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Broad Maiden', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Broad Legged', source: 'Dropped by Fever Horse'},
  {name: 'Broad Zhen', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Broad Tu Wan', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Flame Sword', source: 'Begin Volume 2 with it'},
  {name: 'Broad Wings', source: 'Dropped by Fate Crabs'},
  {name: 'Broad Guiren', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Broad Seigen', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Broad Kuajie', source: 'Dropped by Anchor Bind'},
  {name: 'Broad Sheaf', source: 'Dropped by Scissor Byte'},
  {name: 'Broad Fenlong', source: 'Dropped by Blind Pain'},
  {name: 'Heine\'s Shadow', source: 'Defeat Dopple vol 2'},
  {name: 'Broad Otome', source: 'Weapon Shop Breg Epona'},
  {name: 'Silad', source: 'Story Event Vol 3'},
  {name: 'Broad Dowan', source: 'Weapon Shop Tartarga'},
  {name: 'Broad White', source: 'Trade with Sagittarius'},
  {name: 'Deadly Fearblade', source: 'Post Game Arena Challenge Vol 3'},
  {name: 'Scythe Shouxiao', source: 'Vol 2 Job Extention'},
  {name: 'Scythe Hook', source: 'Buy from kinights guild shop (Dol Dona)'},
  {name: 'Ticking Death', source: 'Lost Weapon'},
  {name: 'Scythe Bite', source: 'Buy from Kestrel Guild Dol Dona'},
  {name: 'Scythe Hidaru', source: 'Trade From Alkaid or buy at Knights Guild (Dol Dona)'},
  {name: 'Scythe Toge', source: 'Weapon Shop Breg Epona'},
  {name: 'Scythe Dakini', source: 'Weapon Shop Tartarga'},
  {name: 'Goddess Scythe', source: 'Story Character Starting Weapon'},
  {name: 'Heine\'s Zero', source: 'Defeat Dopple Vol 2 twice'},
  {name: 'Gun Steel', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Gun Fu Yue', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Water Bayonet', source: 'Kuhnï¿¾fs Starter weapon Vol 1'},
  {name: 'Gun Waves', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Gun Ocher', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Gun Hong', source: 'Trap Chest(Delta) Returning Blue Silver Windup Box'},
  {name: 'Gun Lion', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Gun Bead', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Silent Jade', source: 'Lost Weapon'},
  {name: 'Gun Fisher', source: 'Dropped by Gobtank 75'},
  {name: 'Gun Petal', source: 'Weapon Shop Breg Epona'},
  {name: 'Gun Luna', source: 'Weapon Shop Tartarga'},
  {name: 'Gun Garma', source: 'Trade with Sidewinder or IGA'},
  {name: 'Blade Guifel', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Blade Fern', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Blade Thorns', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Blade Thread', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Spider Karma', source: 'Post Game Character starts with it'},
  {name: 'Crimson Sword', source: 'Antares Starter Weapon'},
  {name: 'Blade Sun', source: 'Dropped by Goblin Knight'},
  {name: 'Princess Blade', source: 'Enderanceï¿¾fs Starter Weapon Vol 2'},
  {name: 'Blade Luer', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Blade Rivet', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Sarasvati Katana', source: 'Story Character Starting Weapon'},
  {name: 'Tempting Rose', source: 'Lost Weapon'},
  {name: 'Blade Rank', source: 'Buy from knights Guild Dol Dona'},
  {name: 'Empty Mirage', source: 'Post Game Character starts with it'},
  {name: 'Empty Shadow', source: 'Post Game Character starts with it'},
  {name: 'Blade Frost', source: 'Weapon Shop Breg Epona'},
  {name: 'Blade Seki', source: 'Weapon Shop Tartarga'},
  {name: 'Blade Jijo', source: 'Trade with Nogmung'},
  {name: 'Tiger Fist', source: 'Piï¿¾fs Starter Weapon'},
  {name: 'Fist Altair', source: 'Dropped by Gan Ziger (or any element Ziger)'},
  {name: 'Fist Talon', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Fist Fairy', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Stained Wing', source: 'Lost Weapon'},
  {name: 'Fist Thrush', source: 'Buy from knights Guild Dol Dona'},
  {name: 'Fist Claw', source: 'Buy from knights guild Breg Epona'},
  {name: 'Feline Soul', source: 'Hidden Character Forest of Pain Starter Weapon'},
  {name: 'Fist Hisa', source: 'Weapon Shop Tartarga'},
  {name: 'Golden Spear', source: 'Piros Starter Weapon'},
  {name: 'Lance Yantie', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Lance Law', source: 'Trap box in (Delta)Adoring Grieving Windup Box (Random)'},
  {name: 'Lance Xiong', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Lance Tulong', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Lance Snake', source: 'Dropped by Sea Trident'},
  {name: 'Lance Quake', source: 'Weapon Shop Breg Epona'},
  {name: 'Lance Rook', source: 'Weapon Shop Tartarga'},
  {name: 'Lance Tower', source: 'Trade with yamato_nadeshiko'},
  {name: 'Spell Xialin', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Spell Xinzhu', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Spell Baiyan', source: 'Dropped by Goblin Abyss'},
  {name: 'Spell Omen', source: 'Trap box in (Delta)Adoring Military Windup Box (Random)'},
  {name: 'Spell Ji Yi', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Dancing Haze', source: 'Lost Weapon'},
  {name: 'Spell Noble', source: 'Buy from knights guild Dol Dona'},
  {name: 'Enchanted Staff', source: 'Post Game Character starts with'},
  {name: 'Summer Staff', source: 'Post Game Arena Challenge Vol 3'},
  {name: 'Magic Amber', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Magic Hosei', source: 'Weapon Shop in Mercenary District (Mac Anu)'},
  {name: 'Magic Nymph', source: 'DX Weapon Shop in Alchemy District (Mac Anu)'},
  {name: 'Magic Crest', source: 'Dropped by Goblin Sage'},
  {name: 'Magic Huawen', source: 'Buy from Weapons shop(Dol Dona)'},
  {name: 'Ogre\'s Heaven', source: 'Sakubo Starter Weapon'},
  {name: 'Infinite Spiral', source: 'Lost Weapon'},
  {name: 'Magic Dielin', source: 'Dropped by Break Pillar'},
  {name: 'Magic Ji Fu', source: 'Weapon Shop Breg Epona'},
  {name: 'Magic Fumon', source: 'Weapon Shop Tartarga'},
  {name: 'Magic Cloud', source: 'Trade with NAOO'},
  {name: 'Fan Jasper', source: 'Weapon Shop Dol Dona'},
  {name: 'Voice Usurper', source: 'Story Character Starts with it'},
  {name: 'Dark Crow', source: 'Story Character Starts with it'},
  {name: 'DG-X', source: 'Story Event'},
  {name: 'DG-Y', source: 'Prize for Block\'s 51-54 of Forest of Pain (Kill Six Enemy Parties)'},
  {name: 'DG-Z', source: 'Last boss of Forest of Pain'},
  {name: 'DG-0', source: 'Beat Dopple after getting DG-X'},
]