export default [
  {name: 'Spin Gai Gu', type: 'Spin', lvl: '1', source: 'Starting Weapon'},
  {name: 'Spin Kouga', type: 'Spin', lvl: '4', source: 'Mercenary Area Weapon Shop'},
  {name: 'Spin Man Que', type: 'Spin', lvl: '8', source: 'Mercenary Area Weapon Shop'},
  {name: 'Spin Rasetu', type: 'Spin', lvl: '14', source: 'Mercenary Area Weapon Shop'},
  {name: 'Spin Corpse', type: 'Spin', lvl: '18', source: 'Trade with Ninjato'},
  {name: 'Spin Locust', type: 'Spin', lvl: '23', source: 'A reward for saving people from PKers'},
  {name: 'Spin Ban Mu', type: 'Spin', lvl: '26', source: '|Kestral Guild Merchant (Water Ban Mu)'},
  {name: 'Spin Piney', type: 'Spin', lvl: '30', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Spin Axe', type: 'Spin', lvl: '35', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Spin Needle', type: 'Spin', lvl: '35', source: 'Buy from Kestral Guild Merchant'},
  {name: "Ripper's Blade", type: 'Spin', lvl: '45', source: 'Kill all of the Blacklisted PKers'},
  {name: 'Broad Demon', type: 'Broad', lvl: '1', source: 'Mercenary Area Weapon Shop'},
  {name: 'Broad Wheel', type: 'Broad', lvl: '10', source: 'Mercenary Area Weapon Shop'},
  {name: 'Broad Maiden', type: 'Broad', lvl: '15', source: 'Mercenary Area Weapon Shop'},
  {name: 'Broad Legged', type: 'Broad', lvl: '20', source: 'Recieve after completing Job Extension'},
  {name: 'Broad Zhen', type: 'Broad', lvl: '25', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Broad Tu Wan', type: 'Broad', lvl: '30', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Flame Sword', type: 'Broad', lvl: '32', source: 'Receive after the 2nd Arena Tournament'},
  {name: 'Broad Wings', type: 'Broad', lvl: '43', source: 'Trade with IGA (Wrath Wings)'},
  {name: 'Gun Steel', type: 'Gun', lvl: '1', source: 'Mercenary Area Weapon Shop'},
  {name: 'Gun Fu Yue', type: 'Gun', lvl: '8', source: 'Mercenary Area Weapon Shop'},
  {name: 'Gun Waves', type: 'Gun', lvl: '24', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Gun Ocher', type: 'Gun', lvl: '31', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Water Bayonet', type: 'Gun', lvl: '13', source: 'Trade with Kuhn'},
  {name: 'Gun Hong', type: 'Gun', lvl: '41', source: 'Trade with Sidewinder (Fire Hong)'},
  {name: 'Blade Guifei', type: 'Blade', lvl: '1', source: 'Mercenary Area Weapon Shop'},
  {name: 'Blade Fern', type: 'Blade', lvl: '4', source: 'Mercenary Area Weapon Shop'},
  {name: 'Blade Thorns', type: 'Blade', lvl: '10', source: 'Mercenary Area Weapon Shop'},
  {name: 'Blade Thread', type: 'Blade', lvl: '17', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Blade Sun', type: 'Blade', lvl: '35', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Tiger Fist', type: 'Fist', lvl: '14', source: 'Trade with Pi'},
  {name: 'Fist Altair', type: 'Fist', lvl: '32', source: 'Trade with Mihirogi (Poison Altair)'},
  {name: 'Golden Spear', type: 'Lance', lvl: '15', source: 'Trade with Piros the 3rd'},
  {name: 'Lance Yantie', type: 'Lance', lvl: '24', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Lance Law', type: 'Lance', lvl: '42', source: 'Trade with Aralagi'},
  {name: 'Spell Xialin', type: 'Spell', lvl: '1', source: 'Mercenary Area Weapon Shop'},
  {name: 'Spell Xinzhu', type: 'Spell', lvl: '15', source: 'Mercenary Area Weapon Shop'},
  {name: 'Spell Baiyan', type: 'Spell', lvl: '32', source: 'Buy from Kestral Guild Merchant'},
  {name: 'Spell Omen', type: 'Spell', lvl: '38', source: 'Trade with NAOO (Wind Omen)'},
  {name: 'Magic Amber', type: 'Magic', lvl: '1', source: 'Mercenary Area Weapon Shop'},
  {name: 'Magic Hosei', type: 'Magic', lvl: '15', source: 'Mercenary Area Weapon Shop'},
  {name: 'Magic Nymph', type: 'Magic', lvl: '28', source: 'Buy from DXWeapon Shop Alchemy Sector'},
  {name: 'Magic Crest', type: 'Magic', lvl: '37', source: 'Trade with Nagare (Sleep Crest)'},
]
